### PR TITLE
Change log level to info.

### PR DESCRIPTION
**Pull request by jordansissel**
I also moved the log message to be structured.

For #372

### CODE REVIEW

**Comment by untergeek** [comment]
What?  No update to the Changelog?  Version bump? :wink:

**Comment by jordansissel** [comment]
*hangs head*

**Comment by untergeek** [comment]
Awesome.  LGTM™

**Comment by jordansissel** [comment]
Will wait on travis to complete before merging. <3

**Comment by untergeek** [comment]
Weird.  The PR build failed, but the push build passed.  Is that okay, @jordansissel ?

**Comment by jordansissel** [comment]
@untergeek funky (re: build failure vs push build pass). Seems OK to me ;P

**Pull request closed without merging**
