### PR TITLE
Doc: Add v8 to ecs_compatibility options

### PR DESCRIPTION
**Pull request by karenzone**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by karenzone** [comment]
@kares or @yaauie: Is this a change that we need to make?  Thanks for looking.

**Review by kares — COMMENTED** [review]
:+1: we do want this to be documented.

the template itself will be v1 even for v8 up till 8.0 is actually released (ECS release 8.0), unsure here whether that is worth mentioning - in my opinion it's transient and not necessary.

**Comment by kares** [comment]
> the template itself will be v1 even for v8 up till 8.0 is actually released (ECS release 8.0), unsure here whether that is worth mentioning - in my opinion it's transient and not necessary.

actually, since https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1062 there's not a BEAT v8 template being shipped.
v1 template also got an update but this isn't mentioned (whether it's worth specifying might be up for discussion)

**Comment by karenzone** [comment]
@kares 
>the template itself will be v1 even for v8 up till 8.0 is actually released (ECS release 8.0)

Is this accurate now that 8.0 has shipped?

**Comment by kares** [comment]
> Is this accurate now that 8.0 has shipped?

That has changed recently with https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1062 ... seems like we generated the v8 from the upstream (unreleased at that time) ECS v8 files.

**Review by kares — APPROVED** [review]

**Comment by karenzone** [comment]
PENDING PUBLISHING: CI not green

**Pull request merged**
