### PR TITLE
Hide credentials in exceptions and log messages.

### LINKED ISSUE #482: Passwords in logstash logs partially visible
I'm using logstash version 5.0.0 beta 1. I have a output configuration listed as:

> output {
> elasticsearch {
> hosts => ["xxx.xxx.local:9200"]
> index => "land-%{+YYYY.MM}"
> user => "elastic"
> password => "changeme"
> }
> }

For some reason its failing to connect to ES v5.0.0 beta 1 (not saying this is a bug, I'm investigating this separately) however I spotted in the logs for logstash I can see that the password has been hidden in some places but not others. Unclear if that is intentional or not? See below:

`[2016-09-22T22:42:31,953][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://~hidden~:~hidden~@xxx.xxx.local:9200][Manticore::SocketTimeout] Read timed out {:url=>#<URI::HTTP:0x5eecb836 URL:http://elastic:changeme@xxx.xxx.local:9200>, :error_message=>"Elasticsearch Unreachable: [http://~hidden~:~hidden~@xxx.xxx.local:9200][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}`

### PR DESCRIPTION
**Pull request by jordansissel**
Fixes #482

### CODE REVIEW

**Comment by andrewvc** [comment]
This is weird. The SafeURI class was added to logstash core so that we would't need to do stuff like use the SafeURL class. The idea was to make it secure by default.

I wonder if this object has been converted to a regular URI class. by accident at some point?

**Comment by andrewvc** [comment]
[SafeURI](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/safe_uri.rb)

**Comment by andrewvc** [comment]
I'll add that I'd prefer to figure out what happened here and have it be secure by default rather than force us to try to capture every logging use case of a URI which is more fragile as code is changed.

**Comment by andrewvc** [comment]
Oh, I guess I never finished / merged this PR https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/450, WDYT about this approach @jordansissel ? I like the implicit safety of it.

**Comment by suyograo** [comment]
@andrewvc Can we go with @jordansissel approach for 5.0 RC1 and then fix it for a point release using your PR #450 ? This will fix #482 and we can take time to finish up #450

**Comment by andrewvc** [comment]
@suyograo #450 is very close, the main issue was dependency errors in LS core causing unit tests to fail.

**Comment by andrewvc** [comment]
@suyograo hmmm, nm that, I'm OK to go with @jordansissel 's solution for now.

**Comment by andrewvc** [comment]
LGTM

**Pull request merged**
