### PR TITLE
Remove the build time jar dependency installation and embedded the jars instead

### PR DESCRIPTION
**Pull request by purbon**
Clean up jar dependencies code and so we end embedded dependencies the same gem. To do so I introduced a common code to load jars so we aim to simplify the management of jars in the long run. This code is actually using a module extracted into a common gem (logstash-devutils).

Version 0.2.1 bump

### CODE REVIEW

**Comment by talevy** [comment]
error when attempting to run:

```
(pr/101)$ bundle exec rspec
Using Accessor#strict_set for specs
NoMethodError: undefined method `load_runtime_jars!' for LogStash::Environment:Module
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/lib/logstash-output-elasticsearch_jars.rb:5
          require at org/jruby/RubyKernel.java:1071
          require at /Users/tal/.rvm/gems/jruby-1.7.18/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch.rb:1
          require at org/jruby/RubyKernel.java:1071
          require at /Users/tal/.rvm/gems/jruby-1.7.18/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch.rb:11
          require at org/jruby/RubyKernel.java:1071
          require at /Users/tal/.rvm/gems/jruby-1.7.18/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch/protocol.rb:1
             load at org/jruby/RubyKernel.java:1087
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch/protocol.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/spec/outputs/elasticsearch/protocol_spec.rb:1
           (root) at /Users/tal/Code/es/talevy-logstash-output-elasticsearch/spec/outputs/elasticsearch/protocol_spec.rb:2
           (root) at /Users/tal/.rvm/gems/jruby-1.7.18/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/tal/.rvm/gems/jruby-1.7.18/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896

```

**Comment by talevy** [comment]
Tests pass under this new scheme. when pinning `logstash-core` gem to https://github.com/elastic/logstash/pull/2980.

**Comment by purbon** [comment]
@talevy does this means, after https://github.com/elastic/logstash/pull/2980 gets in, this is ok to be merged?

**Comment by jsvd** [comment]
tested plugin on logstash http://elastic/logstash#2980 using :path, LGTM

**Pull request closed without merging**
