### PR TITLE
Sane retry logic!

### LINKED ISSUE #321: Retry logic does the wrong thing
Currently our retry logic is the following:
1. Retry [409, 429, 503] up `max_attempts` times per batch.
2. Retry network errors infinitely.

As @gingerwizard pointed out this all makes no sense. We would expect 429/503 to retry infinitely. These both mean that Elasticsearch is just too busy to do anything useful.

For the 409 use case there's no reason to retry on the ES output. We should let Elasticsearch handle that with `retry_on_conflict`.

The great thing about this is we'll need _less_ code in this plugin for better performance / functionality!

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes #321

### CODE REVIEW

**Comment by suyograo** [comment]
@andrewvc can you update the docs too?

**Comment by andrewvc** [comment]
@suyograo aye captain, will do monday!

**Comment by untergeek** [comment]
Sane... I like it!  LGTM™ after the docs have been improved.

**Comment by andrewvc** [comment]
@untergeek @suyograo documentation has been updated. How's it look now?

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
