### PR TITLE
Refactored code sharing to play nicer with java plugin

### PR DESCRIPTION
**Pull request by andrewvc**
Code in support of https://github.com/logstash-plugins/logstash-output-elasticsearch_java/pull/29

### CODE REVIEW

**Comment by untergeek** [comment]
So much easier to read!  This is beautiful now (and less intimidating).

**Comment by andrewvc** [comment]
Thanks @untergeek does that qualify as an LGTM?

**Comment by untergeek** [comment]
Quite so!

**Comment by andrewvc** [comment]
Thanks @untergeek !

**Pull request closed without merging**
