### PR TITLE
add parent parameter

### PR DESCRIPTION
**Pull request by nintra**
for parent/child relationships as discussed in #129

### CODE REVIEW

**Comment by suyograo** [comment]
@nintra could you please add tests using a real ES server to validate this behaviour? Let me know if you need help with writing the tests. See here for examples: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/spec/outputs/elasticsearch_spec.rb

**Comment by nintra** [comment]
@suyograo 
sorry, i don't write ruby and don't have the necessary tools installed. i just wanted to add the functionality mentioned by #129 because i needed it myself and others might too. i guess it would be better if somone more experienced with ruby & testing could check it.

My changes are very minor. Just getting a new parameter 'parent' and send it through to elasticsearch.

Sorry that i can't help more.

**Comment by andrewvc** [comment]
While this code has merit, given that there's no motion to add tests here I'm going to close it for now. If you'd like to reopen it please leave a comment!

**Comment by drdebian** [comment]
I really would like to see this new parameter make it into logstash. How do I write a suitable test?

**Comment by alaviamir** [comment]
+1

**Comment by andrewvc** [comment]
@alaviamir  Unfortunately we have no plans to reopen this without someone willing to write the tests. If you'd like to, please let us know.

**Pull request closed without merging**
