### PR TITLE
Make error messages more verbose and easier to parse by humans

### PR DESCRIPTION
**Pull request by bobrik**
It wasn't obvious why nginx logs report 200 OK, but logstash complains about error code 429.

Error messages looked kind of messy and hard to understand, I moved important things up front. I'm still curious what this tells me:

```
:message=>"es:9200 failed to respond", :class=>"Manticore::ClientProtocolException"
```

### CODE REVIEW

**Comment by suyograo** [comment]
@bobrik can you rebase with master?

**Comment by bobrik** [comment]
Rebased

**Comment by bobrik** [comment]
Was it really my mistake that build failed?

**Comment by bobrik** [comment]
Not sure if it was worth rebasing

**Comment by andrewvc** [comment]
@bobrik Apologies for the delay here. I'd love to accept this patch! Thank you so much :)

Would you mind fixing the merge conflict and updating the CHANGELOG / gemspec so I can release this as 2.5.2?

**Comment by bobrik** [comment]
Done

**Comment by andrewvc** [comment]
Hmmm, we're getting some weird test failures. I'll sort those out on monday.

**Comment by bobrik** [comment]
Any news?

**Comment by suyograo** [comment]
I rebased and will merge. The tests seem to pass when I restarted it. https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/builds/112148004

**Pull request closed without merging**
