### PR TITLE
Set ssl options regardless of :ssl true or false

### LINKED ISSUE #388: https URLs should set ssl options
Using an HTTPS URL will ignore custom keystore settings, this needs to be fixed.

### PR DESCRIPTION
**Pull request by jsvd**
instead of only formatting ssl options if :ssl => true, always do it.

This allows ssl settings to be used if :ssl is set to false but the URL passed in the hosts array uses the https schema (i.e. `https://..`)

fixes #388

### CODE REVIEW

**Comment by andrewvc** [comment]
LGTM

**Comment by andrewvc** [comment]
@jsvd do you mind squashing and rebasing? jarvis can't merge this.

**Comment by andrewvc** [comment]
@jsvd what is the purpose of this PR? What feature does it enable?

**Comment by jsvd** [comment]
@andrewvc I edited the PR description to describe its purpose

**Comment by andrewvc** [comment]
@jsvd as I wrote in https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/388 I don't think this should work that way. Maybe we should continue the discussion there?

**Comment by jsvd** [comment]
this has been fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/e7259de52f88643cc3311ce73d4dfa4663041a87

**Pull request closed without merging**
