### PR TITLE
Extend retry HTTP codes

### PR DESCRIPTION
**Pull request by dropje86**
When using a service like Elastic Cloud there are more possible
  recoverable HTTP error codes because there is a proxy in between
  the ES data nodes and the client.
  Extend the list of retry codes with these errors.

### CODE REVIEW

**Comment by dropje86** [comment]
I understand that there is a DLQ now but these return codes are common in situations where a reverse proxy sits in front of Elastic during "graceful" shutdowns, upgrades etc.. 404's are either a misconfiguration in Logstash -> ES endpoints or temporary missing routes in the proxy. It would also be fine if retry and DLQ codes were configurable but I feel these are generic sane defaults.

**Comment by jordansissel** [comment]
@dropje86 I haven't looked at the code (CLA not signed?), but about your 404 comment. Elasticsearch itself returns 404 in certain situations and we decided this means we should DLQ it (for example, writing to an index that doesn't exist, I think, will return 404 for the status.

**Comment by dropje86** [comment]
Hi @jordansissel CLA is signed and shows okay on my side. The 404 is very unlikely to be returned with writing to a non-existing index as in 99% of the use cases `action.auto_create_index` is enabled on Elasticsearch (also the default).

**Comment by dropje86** [comment]
According to this issue: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/626 it might also be a good idea to include 500 (internal server error) in the retry codes.

**Comment by dropje86** [comment]
Looking at the status codes again for me it doesn't make real sense to have `CONFLICT_CODE` in there. I'd say that is a perfect use case for DLQ apart from a 400 (Bad Request), or am I missing something?

**Comment by andrewvc** [comment]
First, let me say this is a great PR.

I think there's some complication because status codes are used in two places:

1. As the code of the HTTP response
2. As the code, per-event, in the bulk API

In these two contexts they mean two different things.

In the case of a 404 it means that the endpoint is missing (which is not an ES error, only a proxy error) in the context of the HTTP request, while it means an individual doc does not exist (useful for an update operation) in the context of a single event in the bulk request.

I agree that a 404 at the request level should be retried, but our handling of a 404 at the doc level is currently correct. We'll need to split this error code list into two different sets of error codes depending on *where* the error happens.

**Comment by andrewvc** [comment]
I've rebased and added a commit on top of this in #640 to address this important issue. Would love your thoughts there @dropje86

**Comment by andrewvc** [comment]
Closing this since this was merged in #640 and a new gem just published in the 8.x series. A new 7.4.0 version will be published soon as well with this backported

**Pull request closed without merging**
