### PR TITLE
choose default template based on es version

### PR DESCRIPTION
**Pull request by jsvd**
during template installation, query ES to check the version and if the default template is to be used, choose which one based on ES major version

TODO:
- [x] have different templates for 2x and 5x

fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/401

### CODE REVIEW

**Comment by suyograo** [comment]
Whats up with the integration tests?

**Comment by jsvd** [comment]
Missing the templates :)

**Comment by suyograo** [comment]
@jsvd here's the default template for 2.x: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/b85e72e8c160100a84a6ebc341fda88f58de0999/lib/logstash/outputs/elasticsearch/elasticsearch-template.json

For 5.x you can copy what we have now in master.

**Comment by jsvd** [comment]
@suyograo I think we need an es 1.x default template too 😆 https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/builds/146423290

**Comment by untergeek** [comment]
LGTM™ and tests pass for me locally.

**Comment by untergeek** [comment]
Tests pass for me locally, but I notice that the Travis CI tests are not passing, and that’s because the template testing is ​_only_​ for ES major versions 2 and 5: https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/jobs/146423305

do we want to remove ES 1.7.x testing from Travis?

**Comment by suyograo** [comment]
we should use the 2.x template in 1.x as well. That has worked in the past. 1.x is still popular, so I'd like to continue testing against it

**Comment by untergeek** [comment]
Will do another quick PR to add in support for v1 to use the v2 template.

**Pull request closed without merging**
